# ╭───────────────────────╮
# │ environment variables │
# ╰───────────────────────╯
# 📖 https://github.com/DreamMaoMao/mangowc/wiki#env-setting

env=QT_QPA_PLATFORMTHEME,qt5ct
env=

# ╭─────────╮
# │ startup │
# ╰─────────╯
# 📖 https://github.com/DreamMaoMao/mangowc/wiki#exec-setting

# enabled our desktop portal as wlr
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots

# enable mangowc's target service for systemd-based services
exec-once=systemctl --user start hyprland-session.target

exec-once=sway-audio-idle-inhibit
exec-once=kdeconnect-indicator
