# ╭───────────────────────╮
# │ environment variables │
# ╰───────────────────────╯
# 📖 https://github.com/DreamMaoMao/mangowc/wiki#env-setting

env=QT_QPA_PLATFORMTHEME,qt5ct

# ╭─────────╮
# │ startup │
# ╰─────────╯
# 📖 https://github.com/DreamMaoMao/mangowc/wiki#exec-setting

exec-once=sway-audio-idle-inhibit
exec-once=kdeconnect-indicator
